name: Upload to PyPi
on: 
  release:
    types: [ created ]

jobs:
  upload:
    name: upload
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - uses: Gr1N/setup-poetry@v4
      with:
        poetry-version: 1.0.0
    - run: poetry run python -m pip install --upgrade pip
    - run: poetry install
    - run: poetry publish --build
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{secrets.PYPI_TOKEN}}